# Generated by Django 4.2.4 on 2023-09-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_useraccount_managers_userpaymentinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpaymentinfo",
            name="payed_ceo",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="userpaymentinfo",
            name="payed_cto",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
