# Generated by Django 4.2.4 on 2023-09-07 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MtoM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ebitactual1", models.IntegerField()),
                ("ebitactual2", models.IntegerField()),
                ("ebitactual3", models.IntegerField()),
                ("ebitactual4", models.IntegerField()),
                ("ebitactual5", models.IntegerField()),
                ("ebitactual6", models.IntegerField()),
                ("ebitactual7", models.IntegerField()),
                ("ebitactual8", models.IntegerField()),
                ("ebitactual9", models.IntegerField()),
                ("ebitactual10", models.IntegerField()),
                ("ebitactual11", models.IntegerField()),
                ("ebitactual12", models.IntegerField()),
                ("ebittarget1", models.IntegerField()),
                ("ebittarget2", models.IntegerField()),
                ("ebittarget3", models.IntegerField()),
                ("ebittarget4", models.IntegerField()),
                ("ebittarget5", models.IntegerField()),
                ("ebittarget6", models.IntegerField()),
                ("ebittarget7", models.IntegerField()),
                ("ebittarget8", models.IntegerField()),
                ("ebittarget9", models.IntegerField()),
                ("ebittarget10", models.IntegerField()),
                ("ebittarget11", models.IntegerField()),
                ("ebittarget12", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "MtoM",
            },
        ),
    ]
