# Generated by Django 4.2.4 on 2023-09-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentery", "0003_alter_mtom_ebitactual1_alter_mtom_ebitactual10_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mtom",
            name="demo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profitloss",
            name="demo",
            field=models.BooleanField(default=True),
        ),
    ]
