# Generated by Django 4.2.4 on 2023-10-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dataentery", "0004_mtom_demo_profitloss_demo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mtom",
            name="demo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profitloss",
            name="demo",
            field=models.BooleanField(default=False),
        ),
    ]
